/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface InfoContractInterface extends utils.Interface {
  functions: {
    "setInfo(string,string,uint256)": FunctionFragment;
    "getInfo()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "setInfo" | "getInfo"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "setInfo",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getInfo", values?: undefined): string;

  decodeFunctionResult(functionFragment: "setInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getInfo", data: BytesLike): Result;

  events: {
    "InfoUpdated(address,string,uint256,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "InfoUpdated"): EventFragment;
}

export interface InfoUpdatedEventObject {
  updater: string;
  name: string;
  age: BigNumber;
  scolller: string;
}
export type InfoUpdatedEvent = TypedEvent<
  [string, string, BigNumber, string],
  InfoUpdatedEventObject
>;

export type InfoUpdatedEventFilter = TypedEventFilter<InfoUpdatedEvent>;

export interface InfoContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: InfoContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    setInfo(
      _name: string,
      _scolller: string,
      _age: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getInfo(overrides?: CallOverrides): Promise<[string, BigNumber, string]>;
  };

  setInfo(
    _name: string,
    _scolller: string,
    _age: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getInfo(overrides?: CallOverrides): Promise<[string, BigNumber, string]>;

  callStatic: {
    setInfo(
      _name: string,
      _scolller: string,
      _age: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getInfo(overrides?: CallOverrides): Promise<[string, BigNumber, string]>;
  };

  filters: {
    "InfoUpdated(address,string,uint256,string)"(
      updater?: string | null,
      name?: null,
      age?: null,
      scolller?: null
    ): InfoUpdatedEventFilter;
    InfoUpdated(
      updater?: string | null,
      name?: null,
      age?: null,
      scolller?: null
    ): InfoUpdatedEventFilter;
  };

  estimateGas: {
    setInfo(
      _name: string,
      _scolller: string,
      _age: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getInfo(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    setInfo(
      _name: string,
      _scolller: string,
      _age: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
